apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.10.2
    helm:
      values: |
        installCRDs: true
        replicaCount: 1
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 256Mi
        extraEnv:
          - name: AWS_REGION
            value: us-east-2
          - name: AWS_ROLE_ARN
            value: arn:aws:iam::520737738387:role/sidmakes-external-secrets-irsa
          - name: AWS_WEB_IDENTITY_TOKEN_FILE
            value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
          - name: AWS_STS_REGIONAL_ENDPOINTS
            value: regional
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::520737738387:role/sidmakes-external-secrets-irsa
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
