apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: namespaces

resources:
  - n8n-namespace.yaml
  - monitoring-namespace.yaml
  # argocd namespace created by Terraform bootstrap
