apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: DependsOn=db-operator-instances,DependsOn=ingress-nginx,DependsOn=argocd-server-ingress
spec:
  project: default
  source:
    repoURL: https://github.com/sidmakes/gitops
    path: apps/n8n
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - DependsOn=db-operator-instances
      - DependsOn=ingress-nginx
      - DependsOn=argocd-server-ingress
