apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db-operator-instances
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: DependsOn=db-operator-controller
spec:
  project: default
  source:
    repoURL: https://github.com/sidmakes/gitops
    path: apps/db-operator-instances
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: db-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
