apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: production-cluster

resources:
  # Infrastructure
  - ../../infrastructure/namespaces
  
  # Applications
  - ../../apps/n8n/overlays/production

commonLabels:
  cluster: production
  managed-by: gitops
