apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: n8n
        env:
        - name: N8N_LOG_LEVEL
          value: "info"
        - name: N8N_METRICS
          value: "true"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
