apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: n8n-production

namespace: n8n

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

commonLabels:
  environment: production
