apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  credentials:
    source: IRSA


