apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: aws-runtime
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  serviceAccountTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::520737738387:role/space-crossplane-provider-aws
  deploymentTemplate:
    spec:
      template:
        spec:
          containers:
            - name: package-runtime
              env:
                - name: AWS_ROLE_ARN
                  value: arn:aws:iam::520737738387:role/space-crossplane-provider-aws
                - name: AWS_WEB_IDENTITY_TOKEN_FILE
                  value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token


