apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- application.yaml

commonLabels:
  app.kubernetes.io/name: kube-prometheus-stack
  app.kubernetes.io/managed-by: gitops


