apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: aws-load-balancer-controller-values
    files:
      - values.yaml

resources:
  - namespace.yaml
  - application.yaml
