apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-database
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: n8n-database
    creationPolicy: Owner
  data:
    - secretKey: DB_TYPE
      remoteRef:
        key: apps/n8n/database
        property: dbType
    - secretKey: DB_POSTGRESDB_HOST
      remoteRef:
        key: apps/n8n/database
        property: host
    - secretKey: DB_POSTGRESDB_PORT
      remoteRef:
        key: apps/n8n/database
        property: port
    - secretKey: DB_POSTGRESDB_DATABASE
      remoteRef:
        key: apps/n8n/database
        property: database
    - secretKey: DB_POSTGRESDB_USER
      remoteRef:
        key: apps/n8n/database
        property: username
    - secretKey: DB_POSTGRESDB_PASSWORD
      remoteRef:
        key: apps/n8n/database
        property: password
    - secretKey: DB_POSTGRESDB_SSLMODE
      remoteRef:
        key: apps/n8n/database
        property: sslmode
        default: require
    - secretKey: DB_POSTGRESDB_SSL
      remoteRef:
        key: apps/n8n/database
        property: ssl
        default: "true"
    - secretKey: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
      remoteRef:
        key: apps/n8n/database
        property: sslRejectUnauthorized
        default: "false"
