apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: n8n-encryption
    creationPolicy: Owner
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: apps/n8n/encryption
        property: encryptionKey
