apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-database-credentials
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: n8n-database
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_USER
      remoteRef:
        key: rds/sm-postgres/n8n
        property: username
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: rds/sm-postgres/n8n
        property: password
    - secretKey: DATABASE_HOST
      remoteRef:
        key: rds/sm-postgres/n8n
        property: host
    - secretKey: DATABASE_PORT
      remoteRef:
        key: rds/sm-postgres/n8n
        property: port
    - secretKey: DATABASE_NAME
      remoteRef:
        key: rds/sm-postgres/n8n
        property: dbname
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: apps/n8n/encryption
        property: encryptionKey
