apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: n8n-base

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: n8n
  app.kubernetes.io/version: latest
  app.kubernetes.io/managed-by: kustomize
