apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 45.7.1
    helm:
      values: |
        grafana:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
              nginx.ingress.kubernetes.io/ssl-redirect: "false"
              nginx.ingress.kubernetes.io/proxy-redirect-from: "http://"
              nginx.ingress.kubernetes.io/proxy-redirect-to: "https://"
            hosts:
              - grafana.sidmakes.com
          grafana.ini:
            server:
              root_url: https://grafana.sidmakes.com
        
        prometheus:
          ingress:
            enabled: false
          serviceMonitor:
            selfMonitor: true
          prometheusSpec:
            serviceMonitorSelector: {}
            serviceMonitorNamespaceSelector: {}
            podMonitorSelector: {}
            podMonitorNamespaceSelector: {}
            ruleSelector: {}
            ruleNamespaceSelector: {}
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: gp2
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
        
        alertmanager:
          ingress:
            enabled: false
        
        prometheus-node-exporter:
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule
          prometheus:
            monitor:
              enabled: true
              jobLabel: jobLabel
              relabelings:
                - sourceLabels: ["__meta_kubernetes_pod_node_name"]
                  separator: ";"
                  regex: "^(.*)$"
                  targetLabel: node
                  replacement: "$1"
                  action: replace
        
        kube-state-metrics:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
